-- KHATM QURAN - Supabase production-oriented schema
-- Run this whole file in Supabase SQL Editor.
-- Before using the app, enable Auth > Providers > Anonymous Sign-Ins.
-- Also disable "Confirm email" for the synthetic admin accounts used by this
-- static GitHub Pages architecture. The app never uses service_role in browser.

create extension if not exists pgcrypto;

create table if not exists public.khatms (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 80),
  code text not null unique check (code ~ '^[A-Z0-9]{6}$'),
  admin_id uuid not null references auth.users(id) on delete restrict,
  admin_name text not null,
  admin_login_email text not null,
  status text not null default 'active' check (status in ('active','completed','archived')),
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists public.participants (
  id uuid primary key default gen_random_uuid(),
  khatm_id uuid not null references public.khatms(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 40),
  role text not null default 'participant' check (role in ('participant','admin')),
  joined_at timestamptz not null default now(),
  last_active_at timestamptz not null default now(),
  unique(khatm_id, auth_user_id)
);

create table if not exists public.juz_assignments (
  id uuid primary key default gen_random_uuid(),
  khatm_id uuid not null references public.khatms(id) on delete cascade,
  juz_number int not null check (juz_number between 1 and 30),
  participant_id uuid references public.participants(id) on delete set null,
  status text not null default 'free' check (status in ('free','reading','completed')),
  started_at timestamptz,
  completed_at timestamptz,
  unique(khatm_id,juz_number)
);

create table if not exists public.reading_progress (
  id uuid primary key default gen_random_uuid(),
  khatm_id uuid not null references public.khatms(id) on delete cascade,
  participant_id uuid not null references public.participants(id) on delete cascade,
  juz_number int not null check (juz_number between 1 and 30),
  page int not null default 1 check (page > 0),
  updated_at timestamptz not null default now(),
  unique(khatm_id,participant_id,juz_number)
);

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  khatm_id uuid not null references public.khatms(id) on delete cascade,
  participant_id uuid references public.participants(id) on delete set null,
  action text not null,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  khatm_id uuid not null references public.khatms(id) on delete cascade,
  participant_id uuid references public.participants(id) on delete cascade,
  title text not null,
  body text not null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  id uuid primary key default gen_random_uuid(),
  khatm_id uuid not null references public.khatms(id) on delete cascade,
  participant_id uuid references public.participants(id) on delete cascade,
  key text not null,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique(khatm_id,participant_id,key)
);

create index if not exists idx_participants_khatm on public.participants(khatm_id);
create index if not exists idx_assignments_khatm on public.juz_assignments(khatm_id);
create index if not exists idx_activity_khatm on public.activity_logs(khatm_id,created_at desc);
create index if not exists idx_notifications_user on public.notifications(khatm_id,participant_id,created_at desc);

alter table public.khatms enable row level security;
alter table public.participants enable row level security;
alter table public.juz_assignments enable row level security;
alter table public.reading_progress enable row level security;
alter table public.activity_logs enable row level security;
alter table public.notifications enable row level security;
alter table public.settings enable row level security;

create or replace function public.is_khatm_member(p_khatm_id uuid)
returns boolean language sql stable security definer set search_path=public
as $$
  select exists(
    select 1 from public.participants
    where khatm_id=p_khatm_id and auth_user_id=auth.uid()
  ) or exists(
    select 1 from public.khatms where id=p_khatm_id and admin_id=auth.uid()
  );
$$;

create or replace function public.is_khatm_admin(p_khatm_id uuid)
returns boolean language sql stable security definer set search_path=public
as $$
  select exists(select 1 from public.khatms where id=p_khatm_id and admin_id=auth.uid());
$$;

-- Khatms: members can see their own khatm. Creation is only by the new admin.
drop policy if exists "khatms_select_member" on public.khatms;
create policy "khatms_select_member" on public.khatms for select to authenticated
using (public.is_khatm_member(id));

drop policy if exists "khatms_insert_admin" on public.khatms;
create policy "khatms_insert_admin" on public.khatms for insert to authenticated
with check (admin_id=auth.uid());

drop policy if exists "khatms_update_admin" on public.khatms;
create policy "khatms_update_admin" on public.khatms for update to authenticated
using (admin_id=auth.uid()) with check (admin_id=auth.uid());

-- Participants
drop policy if exists "participants_select_members" on public.participants;
create policy "participants_select_members" on public.participants for select to authenticated
using (public.is_khatm_member(khatm_id));

drop policy if exists "participants_update_self" on public.participants;
create policy "participants_update_self" on public.participants for update to authenticated
using (auth_user_id=auth.uid()) with check (auth_user_id=auth.uid());

-- Assignments are changed only through atomic RPCs.
drop policy if exists "assignments_select_members" on public.juz_assignments;
create policy "assignments_select_members" on public.juz_assignments for select to authenticated
using (public.is_khatm_member(khatm_id));

-- Progress belongs to the current participant.
drop policy if exists "progress_select_members" on public.reading_progress;
create policy "progress_select_members" on public.reading_progress for select to authenticated
using (public.is_khatm_member(khatm_id));

drop policy if exists "progress_insert_self" on public.reading_progress;
create policy "progress_insert_self" on public.reading_progress for insert to authenticated
with check (exists(select 1 from public.participants p where p.id=reading_progress.participant_id and p.auth_user_id=auth.uid() and p.khatm_id=reading_progress.khatm_id));

drop policy if exists "progress_update_self" on public.reading_progress;
create policy "progress_update_self" on public.reading_progress for update to authenticated
using (exists(select 1 from public.participants p where p.id=reading_progress.participant_id and p.auth_user_id=auth.uid()))
with check (exists(select 1 from public.participants p where p.id=reading_progress.participant_id and p.auth_user_id=auth.uid() and p.khatm_id=reading_progress.khatm_id));

-- Activity/notifications are read by members; writes happen via RPC.
drop policy if exists "activity_select_members" on public.activity_logs;
create policy "activity_select_members" on public.activity_logs for select to authenticated
using (public.is_khatm_member(khatm_id));

drop policy if exists "notifications_select_members" on public.notifications;
create policy "notifications_select_members" on public.notifications for select to authenticated
using (public.is_khatm_member(khatm_id) and (participant_id is null or exists(select 1 from public.participants p where p.id=participant_id and p.auth_user_id=auth.uid())));

drop policy if exists "notifications_update_self" on public.notifications;
create policy "notifications_update_self" on public.notifications for update to authenticated
using (participant_id is not null and exists(select 1 from public.participants p where p.id=participant_id and p.auth_user_id=auth.uid()))
with check (participant_id is not null and exists(select 1 from public.participants p where p.id=participant_id and p.auth_user_id=auth.uid()));

drop policy if exists "settings_self" on public.settings;
create policy "settings_self" on public.settings for all to authenticated
using (public.is_khatm_member(khatm_id) and (participant_id is null or exists(select 1 from public.participants p where p.id=participant_id and p.auth_user_id=auth.uid())))
with check (public.is_khatm_member(khatm_id) and (participant_id is null or exists(select 1 from public.participants p where p.id=participant_id and p.auth_user_id=auth.uid())));

-- Secure atomic join. This function is deliberately the only public way to create a participant.
create or replace function public.join_khatm(p_code text,p_name text)
returns jsonb
language plpgsql security definer set search_path=public
as $$
declare k public.khatms; p public.participants; cnt int;
begin
  if auth.uid() is null then return jsonb_build_object('success',false,'message','شناسه کاربر ایجاد نشده است.'); end if;
  select * into k from public.khatms where code=upper(trim(p_code)) and status='active';
  if not found then return jsonb_build_object('success',false,'message','کد ختم پیدا نشد یا ختم فعال نیست.'); end if;
  select * into p from public.participants where khatm_id=k.id and auth_user_id=auth.uid();
  if found then
    if p.role='admin' then return jsonb_build_object('success',false,'message','این حساب مدیر است؛ از پنل مدیریت استفاده کنید.'); end if;
    return jsonb_build_object('success',true,'khatm',to_jsonb(k),'participant',to_jsonb(p));
  end if;
  select count(*) into cnt from public.participants where khatm_id=k.id;
  if cnt>=32 then return jsonb_build_object('success',false,'message','ظرفیت این ختم تکمیل شده است.'); end if;
  if trim(p_name)='' then return jsonb_build_object('success',false,'message','نام را وارد کنید.'); end if;
  insert into public.participants(khatm_id,auth_user_id,name) values(k.id,auth.uid(),left(trim(p_name),40)) returning * into p;
  insert into public.activity_logs(khatm_id,participant_id,action,meta) values(k.id,p.id,left(p.name||' وارد ختم شد.',200),'{}');
  return jsonb_build_object('success',true,'khatm',to_jsonb(k),'participant',to_jsonb(p));
end $$;

-- Seed exactly 30 rows for every new khatm.
create or replace function public.seed_khatm(p_khatm_id uuid)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare i int; k public.khatms; p public.participants;
begin
  select * into k from public.khatms where id=p_khatm_id and admin_id=auth.uid();
  if not found then raise exception 'Not authorized'; end if;
  insert into public.participants(khatm_id,auth_user_id,name,role) values(k.id,k.admin_id,k.admin_name,'admin')
  on conflict(khatm_id,auth_user_id) do update set name=excluded.name,role='admin' returning * into p;
  for i in 1..30 loop
    insert into public.juz_assignments(khatm_id,juz_number) values(k.id,i) on conflict do nothing;
  end loop;
  insert into public.activity_logs(khatm_id,participant_id,action) values(k.id,p.id,'ختم جدید ساخته شد.');
  return jsonb_build_object('success',true);
end $$;

-- Atomic first-writer-wins claim.
create or replace function public.claim_juz(p_khatm_id uuid,p_juz_number int)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare a public.juz_assignments; p public.participants;
begin
  select * into p from public.participants where khatm_id=p_khatm_id and auth_user_id=auth.uid() and role='participant';
  if not found then return jsonb_build_object('success',false,'message','شرکت‌کننده معتبر نیست.'); end if;
  select * into a from public.juz_assignments where khatm_id=p_khatm_id and juz_number=p_juz_number for update;
  if not found then return jsonb_build_object('success',false,'message','جزء پیدا نشد.'); end if;
  if a.status<>'free' then return jsonb_build_object('success',false,'message','این جزء همین الان توسط شخص دیگری انتخاب شد.'); end if;
  update public.juz_assignments set participant_id=p.id,status='reading',started_at=now(),completed_at=null where id=a.id returning * into a;
  update public.participants set last_active_at=now() where id=p.id;
  insert into public.activity_logs(khatm_id,participant_id,action,meta) values(p_khatm_id,p.id,p.name||' جزء '||p_juz_number||' را انتخاب کرد.',jsonb_build_object('juz',p_juz_number));
  insert into public.notifications(khatm_id,participant_id,title,body) values(p_khatm_id,null,'جزء جدید انتخاب شد',p.name||' جزء '||p_juz_number||' را انتخاب کرد.');
  return jsonb_build_object('success',true,'assignment',to_jsonb(a));
end $$;

create or replace function public.complete_juz(p_khatm_id uuid,p_juz_number int)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare a public.juz_assignments; p public.participants; done_count int; k public.khatms;
begin
  select * into p from public.participants where khatm_id=p_khatm_id and auth_user_id=auth.uid() and role='participant';
  if not found then return jsonb_build_object('success',false,'message','شرکت‌کننده معتبر نیست.'); end if;
  select * into a from public.juz_assignments where khatm_id=p_khatm_id and juz_number=p_juz_number for update;
  if not found or a.participant_id<>p.id or a.status<>'reading' then return jsonb_build_object('success',false,'message','این جزء متعلق به شما نیست یا قبلاً تکمیل شده است.'); end if;
  update public.juz_assignments set status='completed',completed_at=now() where id=a.id returning * into a;
  update public.participants set last_active_at=now() where id=p.id;
  insert into public.activity_logs(khatm_id,participant_id,action,meta) values(p_khatm_id,p.id,p.name||' جزء '||p_juz_number||' را تکمیل کرد.',jsonb_build_object('juz',p_juz_number));
  insert into public.notifications(khatm_id,participant_id,title,body) values(p_khatm_id,null,'جزء تکمیل شد 🎉',p.name||' جزء '||p_juz_number||' را تکمیل کرد.');
  select count(*) into done_count from public.juz_assignments where khatm_id=p_khatm_id and status='completed';
  if done_count=30 then
    update public.khatms set status='completed',completed_at=now() where id=p_khatm_id returning * into k;
    insert into public.notifications(khatm_id,participant_id,title,body) values(p_khatm_id,null,'ختم قرآن به پایان رسید 🎉','هر ۳۰ جزء با موفقیت تکمیل شد.');
  end if;
  return jsonb_build_object('success',true,'completed_count',done_count);
end $$;

create or replace function public.release_juz(p_khatm_id uuid,p_juz_number int)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare a public.juz_assignments; p public.participants;
begin
  if not public.is_khatm_admin(p_khatm_id) then return jsonb_build_object('success',false,'message','دسترسی مدیر لازم است.'); end if;
  select * into a from public.juz_assignments where khatm_id=p_khatm_id and juz_number=p_juz_number for update;
  if not found then return jsonb_build_object('success',false,'message','جزء پیدا نشد.'); end if;
  if a.status='completed' then return jsonb_build_object('success',false,'message','جزء تکمیل‌شده را نمی‌توان آزاد کرد.'); end if;
  select * into p from public.participants where id=a.participant_id;
  update public.juz_assignments set participant_id=null,status='free',started_at=null,completed_at=null where id=a.id;
  insert into public.activity_logs(khatm_id,participant_id,action,meta) values(p_khatm_id,null,'مدیر جزء '||p_juz_number||' را آزاد کرد.',jsonb_build_object('previous_participant',p.name));
  return jsonb_build_object('success',true);
end $$;

create or replace function public.release_all_juz(p_khatm_id uuid)
returns jsonb language plpgsql security definer set search_path=public
as $$
begin
  if not public.is_khatm_admin(p_khatm_id) then return jsonb_build_object('success',false,'message','دسترسی مدیر لازم است.'); end if;
  update public.juz_assignments set participant_id=null,status='free',started_at=null,completed_at=null where khatm_id=p_khatm_id and status<>'completed';
  insert into public.activity_logs(khatm_id,participant_id,action) values(p_khatm_id,null,'مدیر همه اجزای غیرتکمیل‌شده را آزاد کرد.');
  return jsonb_build_object('success',true);
end $$;

create or replace function public.log_activity(p_khatm_id uuid,p_action text,p_meta jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare p public.participants;
begin
  select * into p from public.participants where khatm_id=p_khatm_id and auth_user_id=auth.uid();
  if not found and not public.is_khatm_admin(p_khatm_id) then return jsonb_build_object('success',false); end if;
  insert into public.activity_logs(khatm_id,participant_id,action,meta) values(p_khatm_id,p.id,left(p_action,200),coalesce(p_meta,'{}'));
  if p.id is not null then update public.participants set last_active_at=now() where id=p.id; end if;
  return jsonb_build_object('success',true);
end $$;

-- Used only to discover the synthetic auth email for a manager login.
-- It does not expose a password or any secret.
create or replace function public.get_admin_login(p_code text)
returns text language sql security definer set search_path=public
as $$ select admin_login_email from public.khatms where code=upper(trim(p_code)) limit 1 $$;

-- Least-privilege grants for browser roles.
grant usage on schema public to anon,authenticated;
grant select on public.khatms,public.participants,public.juz_assignments,public.reading_progress,public.activity_logs,public.notifications,public.settings to authenticated;
grant insert,update on public.khatms to authenticated;
grant insert,update on public.reading_progress to authenticated;
grant update on public.participants to authenticated;
grant update on public.notifications to authenticated;
grant execute on function public.join_khatm(text,text) to anon,authenticated;
grant execute on function public.seed_khatm(uuid) to authenticated;
grant execute on function public.claim_juz(uuid,int) to authenticated;
grant execute on function public.complete_juz(uuid,int) to authenticated;
grant execute on function public.release_juz(uuid,int) to authenticated;
grant execute on function public.release_all_juz(uuid) to authenticated;
grant execute on function public.log_activity(uuid,text,jsonb) to authenticated;
grant execute on function public.get_admin_login(text) to anon,authenticated;

-- Realtime: publish the tables used by the UI.
do $$ begin
  alter publication supabase_realtime add table public.juz_assignments;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.participants;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.khatms;
exception when duplicate_object then null; end $$;
do $$ begin
  alter publication supabase_realtime add table public.notifications;
exception when duplicate_object then null; end $$;

-- Optional helper view for reports (visible only to members through RLS-backed base queries).
create or replace view public.khatm_report as
select k.id,k.name,k.code,k.status,k.created_at,k.completed_at,
       count(distinct p.id)::int as participant_count,
       count(distinct case when j.status='completed' then j.id end)::int as completed_juz
from public.khatms k
left join public.participants p on p.khatm_id=k.id
left join public.juz_assignments j on j.khatm_id=k.id
group by k.id,k.name,k.code,k.status,k.created_at,k.completed_at;

-- Important:
-- Never paste a secret/service_role key into config.js.
-- The browser must use only the publishable/anon key and rely on RLS.
